FROM balenalib/generic-aarch64-ubuntu-node:latest-bionic

MAINTAINER Jamie Curnow <jc@jc21.com>
LABEL maintainer="Jamie Curnow <jc@jc21.com>"

# Packages
RUN apt-get update
RUN apt-get install -y git wget curl expect jq python-magic groff
RUN wget https://bootstrap.pypa.io/get-pip.py -O /tmp/get-pip.py
RUN python /tmp/get-pip.py
RUN pip install --upgrade setuptools
RUN pip install wheel
RUN apt-get install s3cmd
RUN apt-get clean
RUN pip install awscli

WORKDIR /data

