FROM resin/rpi-raspbian:stretch

MAINTAINER Jamie Curnow <jc@jc21.com>
LABEL maintainer="Jamie Curnow <jc@jc21.com>"

# Packages
RUN apt-get update \
    && apt-get install -y git wget curl expect jq python-pip python-magic groff \
    && pip install --upgrade setuptools \
    && pip install wheel \
    && apt-get install s3cmd \
    && apt-get clean \
    && pip install awscli

WORKDIR /data
