FROM resin/rpi-raspbian:stretch

MAINTAINER Jamie Curnow <jc@jc21.com>
LABEL maintainer="Jamie Curnow <jc@jc21.com>"

# Packages
RUN apt-get update
RUN apt-get install -y git wget curl expect jq python-pip python-magic groff
RUN pip install --upgrade setuptools
RUN pip install wheel
RUN apt-get install s3cmd
RUN apt-get clean
RUN pip install awscli

WORKDIR /data
