#!/bin/bash

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "$DIR/.common.sh"

echo -e "${BLUE}❯ ${CYAN}Building docker multiarch: ${YELLOW}${*}${RESET}"

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${DIR}/.." || exit 1

# Buildx Builder
docker buildx create --name "${BUILDX_NAME:-citools}" || echo
docker buildx use "${BUILDX_NAME:-citools}"

docker buildx build \
	--platform linux/amd64,linux/arm64 \
	--progress plain \
	--pull \
	-f Dockerfile \
	$@ \
	.

rc=$?
docker buildx rm "${BUILDX_NAME:-citools}"
echo -e "${BLUE}❯ ${GREEN}Multiarch build Complete${RESET}"
exit $rc
