#!/bin/bash

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "$DIR/.common.sh"

echo -e "${BLUE}❯ ${CYAN}Building docker multiarch: ${YELLOW}${*}${RESET}"

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${DIR}/.." || exit 1

# determine commit if not already set
if [ "$BUILD_COMMIT" == "" ]; then
	BUILD_COMMIT=$(git log -n 1 --format=%h)
fi

# Buildx Builder
docker buildx create --name "${BUILDX_NAME:-citools}" || echo
docker buildx use "${BUILDX_NAME:-citools}"

docker buildx build \
	--build-arg GOPROXY="${GOPROXY:-}" \
	--build-arg GOPRIVATE="${GOPRIVATE:-}" \
	--platform linux/amd64 \
	--progress plain \
	--pull \
	-f Dockerfile \
	$@ \
	.

rc=$?
docker buildx rm "${BUILDX_NAME:-citools}"
echo -e "${BLUE}❯ ${GREEN}Multiarch build Complete${RESET}"
exit $rc
